### ISSUE TITLE
Post / Page Recycle Bin

### ISSUE THREAD

**Issue by JoelNichols** [LogicalCMS/Logical#10]
So essentially the plan is to add a recycle bin of sorts - if a post or page is deleted it shouldn't just be blindly purged from the database but simply removed from public view.

I've considered a few options but I think the easiest and safest way to do this is to simply add a flag to pages and posts that marks them as deleted and when this is set to not show them in the admin UI or the frontend. They could then be shown in a "recycle bin" type UI.

**Comment by dashedstripes** [comment]
Will there be a way to then empty the recycle bin?

**Comment by JoelNichols** [comment]
This feature is actually now implemented in the current version.

The way it's working at present is pages / posts are automatically dropped from the recycle bin after 30 days.

Their slug is reset to a random one whilst in the bin to prevent any conflicts with new pages sharing the same name. They will have a new slug generated for them when restored.

**Comment by JoelNichols** [comment]
Closing issue as this now works in the latest version.
