### ISSUE TITLE
Contact form SMTP not configured

### ISSUE THREAD

**Issue by JoelNichols** [LogicalCMS/Logical#2]
So essentially the mailer for the contact form uses SMTP however it is not configured to do anything at present. 

That is to say, it's there, and it's functional, but the only way to get it to work is to configure it by editing the mailer configuration, which is checked in to git and thus would conflict with any future updates. 

Plan is to try and configure some kind of database driven way of configuring this, as file based configuration should be avoided where possible.

**Comment by dashedstripes** [comment]
Could you set the values to read from the environment?

**Comment by JoelNichols** [comment]
Oh definitely. My only concern is that we've already got a fair amount of env variables set, and I'm thinking it might be better to allow things to be configured via the admin area where possible.

Which actually now has me thinking - could a Dokku / Heroku compatible way of setting env variables from the backend possibly work? I suspect a good reason exists why this isn't possible but if it is that'd be fantastic.

**Comment by JoelNichols** [comment]
I've since decided that yes, it's probably just sensible to set this via environment variables as it's an environment specific issue rather than a site specific one.

**Comment by JoelNichols** [comment]
As we're now using Docker anyway and all configuration is done via environment variables, I can confirm this is the approach we'll be taking.

I'll update this once I've got a free moment to do this.

**Comment by JoelNichols** [comment]
Apparently it takes a ridiculously long time for me to edit a configuration file.

Anyway, yes, SMTP is now configured via environment variables.
